#!/bin/bash
clear
echo "Rodando Datalake"
#cd target
pwd

LOG_LEVEL=INFO
INTERVAL=10 
LOOP=off 
FOLDER_UNICO=0
FOLDER_HOME=/home/mario/Documents 
FOLDER_FULL_NEW=/arquivos_full 
FOLDER_FULL_OLD=/arquivos_full_velhos 
FOLDER_INCREMENTAL_NEW=/arquivos_inc 
FOLDER_INCREMENTAL_OLD=/arquivos_inc_old 
ORIGENS=NO 
TIPOS=NO 
OPTION=2


java -cp . -DLOG_LEVEL=$LOG_LEVEL -DINTERVAL=$INTERVAL -DLOOP=$LOOP -DFOLDER_UNICO=$FOLDER_UNICO -DFOLDER_HOME=$FOLDER_HOME -DFOLDER_FULL_NEW=$FOLDER_FULL_NEW -DFOLDER_FULL_OLD=$FOLDER_FULL_OLD -DFOLDER_INCREMENTAL_NEW=$FOLDER_INCREMENTAL_NEW -DFOLDER_INCREMENTAL_OLD=$FOLDER_INCREMENTAL_OLD -DORIGENS=$ORIGENS -DTIPOS=$TIPOS -DOPTION=$OPTION -jar ./target/csv2anytable.jar
